import { useState } from "react";
import { Sparkle, Copy, Check } from "@phosphor-icons/react";
import { useAiAuthor, useAiAnalyze } from "@/lib/hooks";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { CodeBlock } from "@/components/ui/code-block";
import { Textarea } from "@/components/ui/input";
import { CurvyRect, PillTabs } from "@policyctl/design-system";
import { MonoAnnotation } from "@/components/shared/EmptyState";

const HISTORY_KEY = "policyctl-ai-history";

interface HistoryItem {
  id: string;
  prompt: string;
  output: string;
  mode: "author" | "analyze";
  at: string;
}

export function Ai() {
  const [mode, setMode] = useState<"author" | "analyze">("author");
  const [prompt, setPrompt] = useState("");
  const [output, setOutput] = useState("");
  const [copied, setCopied] = useState(false);

  const authorMut = useAiAuthor();
  const analyzeMut = useAiAnalyze();

  const submit = async () => {
    if (!prompt) return;
    const mut = mode === "author" ? authorMut : analyzeMut;
    try {
      const res = await mut.mutateAsync(prompt);
      const text = mode === "author"
        ? (res as { yaml?: string }).yaml ?? JSON.stringify(res, null, 2)
        : (res as { analysis?: string }).analysis ?? JSON.stringify(res, null, 2);
      setOutput(text);
      saveHistory(prompt, text, mode);
    } catch {
      setOutput("// error: AI request failed");
    }
  };

  const copyOut = async () => {
    if (!output) return;
    await navigator.clipboard.writeText(output);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  };

  return (
    <div className="space-y-24">
      <div className="flex items-center justify-between -mt-1">
        <MonoAnnotation>[ ai / {mode === "author" ? "rule-author" : "analyzer"} ]</MonoAnnotation>
        <PillTabs
          active={mode}
          onChange={(id) => setMode(id as "author" | "analyze")}
          tabs={[
            { id: "author", label: "Author" },
            { id: "analyze", label: "Analyze" },
          ]}
        />
      </div>

      <div className="grid lg:grid-cols-2 gap-16 -mt-1">
        <Card className="p-24 lg:p-32">
          <CurvyRect sides="allSides" />
          <div className="flex items-center gap-8 mb-16">
            <Sparkle className="size-4 text-heat-100" />
            <h3 className="text-label-x-large text-accent-black">Prompt</h3>
          </div>
          <p className="text-body-medium text-black-alpha-64 mb-16">
            {mode === "author"
              ? "Describe a rule in plain English. Get a typed policy."
              : "Paste a policy. Get a critique and suggested improvements."}
          </p>
          <Textarea
            rows={8}
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            placeholder={
              mode === "author"
                ? "e.g. Block any commit that touches db/migrations/ unless it was generated by the CLI"
                : "e.g. paste your .policyctl.yml here for analysis"
            }
          />
          <div className="mt-16 flex items-center gap-8">
            <Button onClick={submit} disabled={(authorMut.isPending || analyzeMut.isPending) || !prompt}>
              {authorMut.isPending || analyzeMut.isPending ? "Generating…" : mode === "author" ? "Author rule" : "Analyze"}
            </Button>
            <Button variant="tertiary" onClick={() => { setPrompt(""); setOutput(""); }}>
              Clear
            </Button>
          </div>
        </Card>

        <Card className="p-24 lg:p-32">
          <CurvyRect sides="allSides" />
          <div className="flex items-center justify-between mb-16">
            <h3 className="text-label-x-large text-accent-black">Output</h3>
            {output && (
              <Button variant="tertiary" size="sm" onClick={copyOut}>
                {copied ? <Check className="size-3 mr-4" /> : <Copy className="size-3 mr-4" />}
                {copied ? "copied" : "copy"}
              </Button>
            )}
          </div>
          {output ? (
            <CodeBlock
              code={output}
              lang={mode === "author" ? "yaml" : "text"}
              title="output"
              showLineNumbers={mode === "author"}
            />
          ) : (
            <pre className="font-mono text-mono-medium text-black-alpha-32 leading-22 p-16">
              {`// ${mode === "author" ? "rule" : "analysis"} will appear here`}
            </pre>
          )}
        </Card>
      </div>

      <History />
    </div>
  );
}

function History() {
  const [items, setItems] = useState<HistoryItem[]>(() => {
    try {
      return JSON.parse(localStorage.getItem(HISTORY_KEY) ?? "[]");
    } catch {
      return [];
    }
  });

  const clear = () => {
    localStorage.removeItem(HISTORY_KEY);
    setItems([]);
  };

  if (items.length === 0) return null;

  return (
    <Card className="p-24 lg:p-32">
      <CurvyRect sides="allSides" />
      <div className="flex items-center justify-between mb-16">
        <h3 className="text-label-x-large text-accent-black">History</h3>
        <Button variant="tertiary" size="sm" onClick={clear}>
          Clear
        </Button>
      </div>
      <ul className="space-y-8 -mt-1">
        {items.slice(0, 10).map((h) => (
          <li
            key={h.id}
            className="flex items-start gap-12 px-12 py-12 -mt-1 relative before:absolute before:inset-0 before:rounded-inherit before:border before:border-border-faint"
          >
            <span className="font-mono text-mono-x-small text-black-alpha-32 shrink-0 pt-2">
              [{h.mode}]
            </span>
            <span className="text-body-medium text-accent-black line-clamp-2 flex-1">
              {h.prompt}
            </span>
            <span className="font-mono text-mono-x-small text-black-alpha-32 shrink-0">
              {h.at}
            </span>
          </li>
        ))}
      </ul>
    </Card>
  );
}

function saveHistory(prompt: string, output: string, mode: "author" | "analyze") {
  try {
    const raw = localStorage.getItem(HISTORY_KEY);
    const items: HistoryItem[] = raw ? JSON.parse(raw) : [];
    items.unshift({
      id: `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
      prompt,
      output,
      mode,
      at: new Date().toISOString().slice(11, 16),
    });
    localStorage.setItem(HISTORY_KEY, JSON.stringify(items.slice(0, 50)));
  } catch {}
}