import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { Sparkle, Copy, Check, Lock, ArrowRight } from "@phosphor-icons/react";
import { useAiAuthor, useAiAnalyze, useBilling } from "@/lib/hooks";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { CodeBlock } from "@/components/ui/code-block";
import { Callout } from "@/components/ui/callout";
import { Textarea } from "@/components/ui/input";
import { CurvyRect, PillTabs } from "@policyctl/design-system";
import { MonoAnnotation } from "@/components/shared/EmptyState";

const HISTORY_KEY = "policyctl-ai-history";

interface HistoryItem {
  id: string;
  prompt: string;
  output: string;
  mode: "author" | "analyze";
  at: string;
}

export function Ai() {
  const [mode, setMode] = useState<"author" | "analyze">("author");
  const [prompt, setPrompt] = useState("");
  const [output, setOutput] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  const { data: billing } = useBilling();
  const authorMut = useAiAuthor();
  const analyzeMut = useAiAnalyze();

  const isPaid = billing?.is_paid ?? false;

  const submit = async () => {
    if (!prompt) return;
    try {
      if (mode === "author") {
        const res = await authorMut.mutateAsync(prompt);
        const text = res.rule ?? JSON.stringify(res, null, 2);
        setOutput(text);
        saveHistory(prompt, text, mode);
      } else {
        const res = await analyzeMut.mutateAsync({ diff: prompt });
        const text = res.summary ?? JSON.stringify(res, null, 2);
        setOutput(text);
        saveHistory(prompt, text, mode);
      }
      setError(null);
    } catch (e: any) {
      const msg = e?.message?.includes("429")
        ? "Rate limited. Please wait a moment and try again."
        : e?.message || "AI request failed. Please try again.";
      setError(msg);
      setOutput("");
    }
  };

  const copyOut = async () => {
    if (!output) return;
    await navigator.clipboard.writeText(output);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  };

  return (
    <div className="space-y-24">
      <div className="-mt-1 flex items-center justify-between">
        <MonoAnnotation>[ ai / {mode === "author" ? "rule-author" : "analyzer"} ]</MonoAnnotation>
        {!isPaid && (
          <Badge tone="accent">
            <Lock className="size-3 mr-4" aria-hidden />
            Paid feature
          </Badge>
        )}
        <PillTabs
          active={mode}
          onChange={(id) => setMode(id as "author" | "analyze")}
          tabs={[
            { id: "author", label: "Author" },
            { id: "analyze", label: "Analyze" },
          ]}
        />
      </div>

      {!isPaid ? (
        <Card className="p-32 lg:p-64">
          <CurvyRect sides="allSides" />
          <div className="text-center">
            <div className="mb-16 inline-flex size-48 items-center justify-center text-heat-100">
              <Lock className="size-8" aria-hidden />
            </div>
            <h2 className="text-title-h4 mb-16">AI rule author &amp; analyzer</h2>
            <p className="mx-auto mb-24 max-w-md text-body-medium leading-26 text-black-alpha-64">
              Generate policy rules from plain-English intent and analyze git diffs for
              violations. This feature is part of the upcoming premium control plane.
            </p>
            <div className="flex items-center justify-center gap-12">
              <Link
                to="/pricing"
                className="inline-flex items-center gap-4 rounded-full bg-heat-100 px-16 py-8 text-label-medium font-medium text-accent-white transition-colors hover:bg-heat-90"
              >
                Join the waitlist
                <ArrowRight className="size-3" aria-hidden />
              </Link>
            </div>
          </div>
        </Card>
      ) : (
        <div className="grid gap-16 lg:grid-cols-2">
          <Card className="p-24 lg:p-32">
            <CurvyRect sides="allSides" />
            <div className="mb-16 flex items-center gap-8">
              <Sparkle className="size-4 text-heat-100" aria-hidden />
              <h2 className="text-label-x-large">Prompt</h2>
            </div>
            <p className="mb-16 text-body-medium text-black-alpha-64">
              {mode === "author"
                ? "Describe a rule in plain English. Get a typed policy."
                : "Paste a git diff here for analysis. Optionally include your policy and repo name."}
            </p>
            <Textarea
              rows={8}
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              placeholder={
                mode === "author"
                  ? "e.g. Block any commit that touches db/migrations/ unless it was generated by the CLI"
                  : "e.g. paste a git diff here for analysis"
              }
            />
            {error && (
              <div className="mt-16">
                <Callout type="danger" title="Request failed">
                  {error}
                </Callout>
              </div>
            )}
            <Button
              className="mt-16 w-full"
              onClick={submit}
              disabled={!prompt || authorMut.isPending || analyzeMut.isPending}
            >
              {authorMut.isPending || analyzeMut.isPending ? "Working…" : "Submit"}
            </Button>
          </Card>

          <Card className="p-24 lg:p-32">
            <CurvyRect sides="allSides" />
            <div className="mb-16 flex items-center justify-between">
              <h2 className="text-label-x-large">Output</h2>
              <Button variant="tertiary" size="sm" onClick={copyOut} disabled={!output}>
                {copied ? <Check className="size-3 mr-4" aria-hidden /> : <Copy className="size-3 mr-4" aria-hidden />}
                {copied ? "Copied" : "Copy"}
              </Button>
            </div>
            {output ? (
              <CodeBlock code={output} lang={mode === "author" ? "yaml" : "markdown"} title="result" />
            ) : (
              <p className="text-body-medium text-black-alpha-64">
                Results appear here after you submit a prompt.
              </p>
            )}
          </Card>
        </div>
      )}

      {isPaid && <History />}
    </div>
  );
}

function loadHistory(): HistoryItem[] {
  try {
    return JSON.parse(localStorage.getItem(HISTORY_KEY) ?? "[]");
  } catch {
    return [];
  }
}

function History() {
  const [items, setItems] = useState<HistoryItem[]>(loadHistory);

  useEffect(() => {
    const reload = () => setItems(loadHistory());
    window.addEventListener("policyctl:ai-history", reload);
    return () => window.removeEventListener("policyctl:ai-history", reload);
  }, []);

  const clear = () => {
    localStorage.removeItem(HISTORY_KEY);
    setItems([]);
  };

  if (items.length === 0) return null;

  return (
    <Card className="p-24 lg:p-32">
      <CurvyRect sides="allSides" />
      <div className="mb-16 flex items-center justify-between">
        <h2 className="text-label-x-large">History</h2>
        <Button variant="tertiary" size="sm" onClick={clear}>
          Clear
        </Button>
      </div>
      <ul className="space-y-8">
        {items.slice(0, 10).map((h) => (
          <li
            key={h.id}
            className="relative flex items-start gap-12 rounded-md border border-border-faint px-12 py-8"
          >
            <span className="shrink-0 pt-2 font-mono text-mono-x-small text-black-alpha-32">
              [{h.mode}]
            </span>
            <span className="line-clamp-2 flex-1 text-body-medium">{h.prompt}</span>
            <span className="shrink-0 font-mono text-mono-x-small text-black-alpha-32">
              {h.at}
            </span>
          </li>
        ))}
      </ul>
    </Card>
  );
}

function saveHistory(prompt: string, output: string, mode: "author" | "analyze") {
  try {
    const items: HistoryItem[] = loadHistory();
    items.unshift({
      id: `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
      prompt,
      output,
      mode,
      at: new Date().toISOString().slice(11, 16),
    });
    localStorage.setItem(HISTORY_KEY, JSON.stringify(items.slice(0, 50)));
    window.dispatchEvent(new Event("policyctl:ai-history"));
  } catch {}
}
