/**
 * Test utilities for CLI integration tests.
 */

import { mkdtempSync, writeFileSync, mkdirSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

/** Create a temp directory and return its path. */
export function tempDir(): string {
  return mkdtempSync(join(tmpdir(), "pc-cli-"));
}

/** Write a .policyctl.yml file to a temp directory and return the path. */
export function writePolicy(dir: string, yaml: string): string {
  const p = join(dir, ".policyctl.yml");
  writeFileSync(p, yaml);
  return p;
}

export const SAMPLE_POLICY = `version: 1
rules:
  - id: no-readme-edits
    scope: hook
    when: { path: "README.md" }
    enforce: block
    description: "Do not edit README.md directly"
  - id: no-secrets
    scope: ci
    when: { diff_regex: "(?i)ghp_[a-z0-9]{30}" }
    enforce: fail
    description: "No hardcoded secrets"
  - id: migration-header
    scope: ci
    when: { path: "db/migrations/**", diff_not_contains: "Generated by make migrate" }
    enforce: block
`;

/** Write a minimal valid policy and return the path. */
export function minimalPolicy(dir?: string): string {
  const d = dir ?? tempDir();
  return writePolicy(d, SAMPLE_POLICY);
}

/** Create a .git/hooks/pre-commit in the given dir. */
export function writeGit(dir: string): string {
  const hooksDir = join(dir, ".git", "hooks");
  mkdirSync(hooksDir, { recursive: true });
  return join(dir, ".git");
}

/** Write a config file to simulate an authenticated user. */
export function writeTestConfig(dir: string): void {
  // This would write to ~/.policyctl/config.json in real usage,
  // but tests should use the override mechanism.
}
