import { mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { evaluateCheck } from "../src/commands/check.js";
import { evaluateHook, eventToHookContext } from "../src/commands/eval.js";
import type { CiContext, HookContext } from "@policyctl/core";

const POLICY = `version: 1
rules:
  - id: migrations
    scope: both
    when: { path: "db/migrations/**", diff_not_contains: "Generated by make migrate" }
    enforce: block
  - id: readme
    scope: hook
    when: { path: "README.md" }
    enforce: block
  - id: secret
    scope: ci
    when: { diff_regex: "(?i)ghp_" }
    enforce: fail
`;

function policyFile(): string {
  const dir = mkdtempSync(join(tmpdir(), "pc-"));
  const p = join(dir, ".policyctl.yml");
  writeFileSync(p, POLICY);
  return p;
}

describe("evaluateCheck (CI / diff surface)", () => {
  const path = policyFile();

  it("blocks a handwritten migration (path matched, signature absent)", () => {
    const ctx: CiContext = {
      files: [{ path: "db/migrations/01.sql", status: "added" }],
      text: "CREATE TABLE x (id int);",
    };
    expect(evaluateCheck(path, ctx).exitCode).toBe(2);
  });

  it("passes a generated migration (signature present)", () => {
    const ctx: CiContext = {
      files: [{ path: "db/migrations/02.sql", status: "added" }],
      text: "Generated by make migrate -- do not edit by hand.",
    };
    expect(evaluateCheck(path, ctx).exitCode).toBe(0);
  });

  it("fails on a secret pattern in the diff", () => {
    const ctx: CiContext = {
      files: [{ path: "config.ts", status: "modified" }],
      text: "const t = 'ghp_abcdefghijklmnopqrstuvwxyz';",
    };
    expect(evaluateCheck(path, ctx).exitCode).toBe(2);
  });

  it("is clean with no relevant changes", () => {
    const ctx: CiContext = { files: [{ path: "src/a.ts", status: "modified" }], text: "x" };
    expect(evaluateCheck(path, ctx).exitCode).toBe(0);
  });
});

describe("evaluateHook (agent hook surface)", () => {
  const path = policyFile();

  it("blocks an edit to README.md", () => {
    const ctx: HookContext = { tool: "Edit", file_path: "README.md" };
    expect(evaluateHook(path, ctx).exitCode).toBe(2);
  });

  it("allows an edit to source", () => {
    const ctx: HookContext = { tool: "Edit", file_path: "src/a.ts" };
    expect(evaluateHook(path, ctx).exitCode).toBe(0);
  });
});

describe("eventToHookContext", () => {
  it("maps a Claude Code PreToolUse event", () => {
    const ctx = eventToHookContext({
      tool_name: "Bash",
      tool_input: { command: "sqlite3 db.sqlite" },
    });
    expect(ctx).toEqual({ tool: "Bash", command: "sqlite3 db.sqlite", file_path: undefined });
  });
});
