import { describe, expect, it } from "vitest";
import { evaluatePolicy } from "../evaluate.js";
import { evaluateRule } from "../matchers.js";
import { loadPolicyFromString } from "../load.js";
import type { CiContext, HookContext, Policy, Rule } from "../types.js";

function rule(over: Partial<Rule> & Pick<Rule, "when" | "enforce" | "scope">): Rule {
  return { id: "r", description: "r", ...over };
}

describe("hook-mode matchers", () => {
  it("matches file_path glob", () => {
    const r = rule({ when: { path: "db/migrations/**" }, enforce: "block", scope: "hook" });
    expect(
      evaluateRule(r, { tool: "Write", file_path: "db/migrations/0001.sql" } as HookContext, "hook"),
    ).toBe(true);
    expect(
      evaluateRule(r, { tool: "Write", file_path: "src/a.ts" } as HookContext, "hook"),
    ).toBe(false);
  });

  it("matches command regex", () => {
    const r = rule({ when: { command: "sqlite3|\\.sql$" }, enforce: "block", scope: "hook" });
    expect(evaluateRule(r, { tool: "Bash", command: "sqlite3 db.sqlite" } as HookContext, "hook")).toBe(true);
    expect(evaluateRule(r, { tool: "Bash", command: "ls" } as HookContext, "hook")).toBe(false);
  });

  it("matches tool exact and regex", () => {
    const exact = rule({ when: { tool: "Bash" }, enforce: "block", scope: "hook" });
    expect(evaluateRule(exact, { tool: "Bash" } as HookContext, "hook")).toBe(true);
    expect(evaluateRule(exact, { tool: "Edit" } as HookContext, "hook")).toBe(false);
    const rx = rule({ when: { tool: "/Edit|Write|MultiEdit/" }, enforce: "block", scope: "hook" });
    expect(evaluateRule(rx, { tool: "MultiEdit" } as HookContext, "hook")).toBe(true);
  });
});

describe("ci-mode matchers", () => {
  const ctx: CiContext = {
    text: "diff --git a/src/foo.ts b/src/foo.ts\n+const x=1;\n+SECRET=ghp_abcdefghijklmnopqrstuvwxyz\n",
    files: [
      { path: "src/foo.ts", status: "modified", patch: "+const x=1;" },
      { path: "src/foo.test.ts", status: "added" },
    ],
  };

  it("diff_contains substring", () => {
    const r = rule({ when: { diff_contains: "ghp_" }, enforce: "fail", scope: "ci" });
    expect(evaluateRule(r, ctx, "ci")).toBe(true);
  });

  it("diff_regex", () => {
    const r = rule({ when: { diff_regex: "(?i)aws_secret_access_key" }, enforce: "fail", scope: "ci" });
    expect(evaluateRule(r, ctx, "ci")).toBe(false);
  });

  it("diff_paths_glob + diff_paths_not_glob (AND)", () => {
    const r = rule({
      when: { diff_paths_glob: "src/**/*.ts", diff_paths_not_glob: "**/*.test.ts" },
      enforce: "warn",
      scope: "ci",
    });
    // has a src file, but ALSO has a test file -> should NOT fire
    expect(evaluateRule(r, ctx, "ci")).toBe(false);

    const ctx2: CiContext = {
      text: "x",
      files: [{ path: "src/bar.ts", status: "modified" }],
    };
    expect(evaluateRule(r, ctx2, "ci")).toBe(true);
  });

  it("path glob in ci matches changed files", () => {
    const r = rule({ when: { path: "src/**/*.ts" }, enforce: "warn", scope: "ci" });
    expect(evaluateRule(r, ctx, "ci")).toBe(true);
  });
});

describe("scope filtering", () => {
  it("hook-only rule does not fire in ci mode and vice versa", () => {
    const hookOnly = rule({ when: { tool: "Bash" }, enforce: "block", scope: "hook" });
    const ciOnly = rule({ when: { diff_regex: "x" }, enforce: "fail", scope: "ci" });
    expect(evaluateRule(hookOnly, { files: [], text: "x" } as CiContext, "ci")).toBe(false);
    expect(evaluateRule(ciOnly, { tool: "Bash" } as HookContext, "hook")).toBe(false);
  });

  it("both rule with mixed matchers fires only on the applicable subset per mode", () => {
    const r = rule({
      when: { path: "db/migrations/**", diff_not_contains: "Generated by make migrate" },
      enforce: "block",
      scope: "both",
    });
    // hook mode: only `path` applies -> fires on any migration write (friction + fast no)
    expect(evaluateRule(r, { tool: "Write", file_path: "db/migrations/01.sql" } as HookContext, "hook")).toBe(true);
    // ci mode: migration file changed WITHOUT the generator signature -> fails the build
    expect(
      evaluateRule(
        r,
        { files: [{ path: "db/migrations/01.sql", status: "added" }], text: "handwritten sql" } as CiContext,
        "ci",
      ),
    ).toBe(true);
    // ci mode: migration file changed WITH the signature -> correctly generated, does not fire
    expect(
      evaluateRule(
        r,
        {
          files: [{ path: "db/migrations/01.sql", status: "added" }],
          text: "Generated by make migrate -- do not edit by hand.",
        } as CiContext,
        "ci",
      ),
    ).toBe(false);
  });
});

describe("evaluatePolicy exit codes", () => {
  const policy: Policy = {
    version: 1,
    rules: [
      { id: "deny", when: { tool: "Bash" }, enforce: "block", scope: "hook" },
      { id: "warn", when: { path: "README.md" }, enforce: "warn", scope: "hook" },
    ],
  };

  it("returns 2 when a deny fires", () => {
    const out = evaluatePolicy(policy, { tool: "Bash" } as HookContext, "hook");
    expect(out.exitCode).toBe(2);
    expect(out.results.map((r) => r.ruleId)).toContain("deny");
  });

  it("returns 1 when only warn fires", () => {
    const out = evaluatePolicy(policy, { tool: "Edit", file_path: "README.md" } as HookContext, "hook");
    expect(out.exitCode).toBe(1);
    expect(out.results[0].ruleId).toBe("warn");
  });

  it("returns 0 when nothing fires", () => {
    const out = evaluatePolicy(policy, { tool: "Edit", file_path: "src/x.ts" } as HookContext, "hook");
    expect(out.exitCode).toBe(0);
    expect(out.results).toHaveLength(0);
  });
});

describe("loadPolicyFromString", () => {
  it("parses a valid policy", () => {
    const p = loadPolicyFromString(`version: 1
rules:
  - id: a
    scope: both
    when: { path: "x/**" }
    enforce: block
`);
    expect(p.rules).toHaveLength(1);
  });

  it("throws on missing rules array", () => {
    expect(() => loadPolicyFromString("version: 1")).toThrow(/rules/);
  });

  it("throws on bad enforce / scope", () => {
    expect(() =>
      loadPolicyFromString("version: 1\nrules:\n  - id: a\n    scope: hook\n    when: { path: x }\n    enforce: nope\n"),
    ).toThrow(/enforce/);
  });
});
