import { describe, expect, it } from "vitest";
import { evaluatePolicy, type EvaluationOutcome } from "../evaluate.js";
import { loadPolicyFromString } from "../load.js";
import type { CiContext, HookContext, Policy } from "../types.js";

describe("vars interpolation", () => {
  const policy: Policy = {
    version: 1,
    vars: { migrations_dir: "db/migrations" },
    rules: [
      {
        id: "m",
        scope: "hook",
        when: { path: "${migrations_dir}/**" },
        enforce: "block",
      },
    ],
  };
  it("interpolates ${name} from policy vars", () => {
    const out = evaluatePolicy(
      policy,
      { tool: "Write", file_path: "db/migrations/01.sql" } as HookContext,
      "hook",
    );
    expect(out.exitCode).toBe(2);
  });
  it("also reads ${name} from environment", () => {
    const p: Policy = {
      version: 1,
      rules: [{ id: "x", scope: "hook", when: { path: "${POLICYCTL_TEST_GLOB}/**" }, enforce: "block" }],
    };
    process.env.POLICYCTL_TEST_GLOB = "secrets";
    const out = evaluatePolicy(p, { tool: "Write", file_path: "secrets/a.txt" } as HookContext, "hook");
    expect(out.exitCode).toBe(2);
    delete process.env.POLICYCTL_TEST_GLOB;
  });
});

describe("OR-groups (all + any)", () => {
  // The rule: "warn if a src/** change is unaccompanied by a test file OR a FORCE_TEST comment"
  const policy: Policy = {
    version: 1,
    rules: [
      {
        id: "src-guard",
        scope: "ci",
        when: { all: [{ diff_paths_glob: "src/**/*.ts" }], any: [{ diff_paths_not_glob: "**/*.test.ts" }, { diff_regex: "FORCE_TEST" }] },
        enforce: "warn",
      },
    ],
  };
  it("does not fire when both a src change and a test change are present (any-branch fails)", () => {
    const ctx: CiContext = { files: [{ path: "src/a.ts", status: "modified" }, { path: "src/a.test.ts", status: "added" }], text: "" };
    expect(evaluatePolicy(policy, ctx, "ci").exitCode).toBe(0);
  });
  it("fires (any-branch via missing test) when only src changes", () => {
    const ctx: CiContext = { files: [{ path: "src/a.ts", status: "modified" }], text: "" };
    expect(evaluatePolicy(policy, ctx, "ci").exitCode).toBe(1);
  });
  it("fires (any-branch via regex) when src change has a FORCE_TEST comment", () => {
    const ctx: CiContext = { files: [{ path: "src/a.ts", status: "modified" }, { path: "src/a.test.ts", status: "added" }], text: "FORCE_TEST" };
    expect(evaluatePolicy(policy, ctx, "ci").exitCode).toBe(1);
  });
});

describe("exceptions allowlist", () => {
  const policy = (enforce: "warn" | "ignore"): Policy => ({
    version: 1,
    rules: [
      {
        id: "m",
        scope: "ci",
        when: { path: "db/migrations/**", diff_not_contains: "Generated by make migrate" },
        enforce: "block",
      },
    ],
    exceptions: [{ rule: "m", enforce }],
  });

  it("downgrades a block to a warning", () => {
    const ctx: CiContext = { files: [{ path: "db/migrations/01.sql", status: "added" }], text: "handwritten" };
    const out = evaluatePolicy(policy("warn"), ctx, "ci");
    expect(out.exitCode).toBe(1);
    expect(out.results[0].enforce).toBe("warn");
    expect(out.results[0].message).toContain("sanctioned exception");
  });
  it("ignores (suppresses) the violation", () => {
    const ctx: CiContext = { files: [{ path: "db/migrations/01.sql", status: "added" }], text: "handwritten" };
    const out = evaluatePolicy(policy("ignore"), ctx, "ci");
    expect(out.exitCode).toBe(0);
    expect(out.results).toHaveLength(0);
  });
});

describe("custom message templating", () => {
  it("interpolates {{ruleId}} and {{path}}", () => {
    const policy: Policy = {
      version: 1,
      rules: [
        {
          id: "no-readme",
          scope: "hook",
          when: { path: "README.md" },
          enforce: "block",
          message: "Blocked {{path}} via rule {{ruleId}}",
        },
      ],
    };
    const out: EvaluationOutcome = evaluatePolicy(
      policy,
      { tool: "Edit", file_path: "README.md" } as HookContext,
      "hook",
    );
    expect(out.results[0].message).toBe("Blocked README.md via rule no-readme");
  });
});

describe("load validation", () => {
  it("accepts vars, tags, exceptions, and group syntax", () => {
    const p = loadPolicyFromString(`version: 1
vars: { d: "db" }
exceptions:
  - rule: m
    enforce: ignore
rules:
  - id: m
    tags: [db]
    scope: both
    when: { all: [{ path: "\${d}/**" }], any: [{ diff_not_contains: "x" }] }
    enforce: block
`);
    expect(p.vars?.d).toBe("db");
    expect(p.exceptions?.[0].enforce).toBe("ignore");
    expect(p.rules[0].tags).toEqual(["db"]);
  });
  it("rejects a group without all/any arrays", () => {
    expect(() =>
      loadPolicyFromString("version: 1\nrules:\n  - id: m\n    scope: hook\n    when: { all: x }\n    enforce: block\n"),
    ).toThrow(/group/);
  });
  it("rejects bad exception enforce", () => {
    expect(() =>
      loadPolicyFromString("version: 1\nrules:\n  - id: m\n    scope: hook\n    when: { path: x }\n    enforce: block\nexceptions:\n  - enforce: ban\n"),
    ).toThrow(/exception/);
  });
});
