// Starter policy templates. This is the "library" that makes the tool useful on day one.
// `policyctl init --template <name>` copies one of these into .policyctl.yml.

export const TEMPLATES: Record<string, string> = {
  default: `version: 1
rules:
  - id: no-readme-edits
    description: 'Agents must not edit README.md.'
    scope: hook
    when: { path: 'README.md' }
    enforce: block
`,
  migrations: `version: 1
rules:
  - id: migrations-via-generator
    description: 'DB migrations must be produced by \`make migrate\`, never handwritten.'
    scope: both
    when:
      path: 'db/migrations/**'
      diff_not_contains: '! Generated by make migrate -- do not edit by hand.'
    enforce: block
`,
  secrets: `version: 1
rules:
  - id: no-secrets-in-commits
    description: 'Reject commits that add obvious secret patterns.'
    scope: ci
    when: { diff_regex: '(?i)(aws_secret_access_key|ghp_|sk-[a-z0-9]{20,})' }
    enforce: fail
`,
  readme: `version: 1
rules:
  - id: no-readme-edits
    description: 'Agents must not edit README.md.'
    scope: hook
    when: { path: 'README.md' }
    enforce: block
`,
  full: `version: 1
rules:
  - id: migrations-via-generator
    description: 'DB migrations must be produced by \`make migrate\`, never handwritten.'
    scope: both
    when:
      path: 'db/migrations/**'
      diff_not_contains: '! Generated by make migrate -- do not edit by hand.'
    enforce: block
  - id: no-readme-edits
    description: 'Agents must not edit README.md.'
    scope: hook
    when: { path: 'README.md' }
    enforce: block
  - id: no-secrets-in-commits
    description: 'Reject commits that add obvious secret patterns.'
    scope: ci
    when: { diff_regex: '(?i)(aws_secret_access_key|ghp_|sk-[a-z0-9]{20,})' }
    enforce: fail
  - id: tests-for-src
    description: 'Source changes under src/ should be paired with test changes.'
    scope: ci
    when:
      diff_paths_glob: 'src/**/*.ts'
      diff_paths_not_glob: '**/*.test.ts'
    enforce: warn
`,
};

export const TEMPLATE_NAMES = Object.keys(TEMPLATES);
