// Inlines the shared policyctl design system into the Worker so the dashboard
// is on-brand without a runtime fetch. Source of truth: packages/design-system.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const dsRoot = join(here, "..", "..", "..", "packages", "design-system", "src");

const tokens = readFileSync(join(dsRoot, "tokens.css"), "utf8");
let components = readFileSync(join(dsRoot, "components.css"), "utf8");
// tokens are imported by components.css; we inline tokens first, so drop the @import.
components = components.replace(/@import\s+["']\.\/tokens\.css["'];?/g, "");

let css = `${tokens}\n${components}`;
// escape for a TS template literal
css = css.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

const out = join(here, "..", "src", "_ds.ts");
writeFileSync(out, `// AUTO-GENERATED by scripts/build-css.mjs — do not edit by hand.\nexport const DS_CSS = \`${css}\`;\n`);
console.log(`[build-css] wrote ${out} (${(css.length / 1024).toFixed(1)} KB)`);
