name: publish

on:
  push:
    tags: ["v*.*.*"]

jobs:
  publish-cli:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: pnpm, registry-url: https://registry.npmjs.org }
      - run: pnpm install
      - run: pnpm --filter @policyctl/core build
      - run: pnpm --filter @policyctl/cli build
      - run: cd packages/cli && npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Create a GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            packages/cli/*.tgz
          generate_release_notes: true
